name: Crum Secret

on:
  push:
  
jobs:
  my_job:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 18 # or desired version

          - name: Install dependencies
            run: npm install

          - name: Run app with secrets
            run: node ${{ github.repository }}/crum/dictionary/scripts/sheets_api_test.js
            env:
              API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }}
