name: Crum Secret

on:
  push:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node /crum/dictionary/scripts/sheets_api_test.js
        env:
          API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }}