name: Crum Secret

on:
  push:
  
env:
  API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ϫ This repository's secret is ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }} for the Google Sheets API Key."
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
          sh ${{ github.workspace }}/crum/dictionary/scripts/sheets_api_test.js
    - run: echo "🍏 This job's status is ${{ job.status }}."
