name: Crum Secret

on:
  push:
  
env:
  API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run app with secrets
        run: cd ./sheets_api_test.js
       
