name: Crum Secret

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run app with secrets
        run: bash -eux sheets_api_test.js
        env:
          API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }}
