name: Crum Secret

on:
  push:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate README file
        run: node /crum/dictionary/scripts/sheets_api_test.js
        env:
          API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY_CRUM_DICTIONARY }}
